// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MarketingService_CreateCampaign_FullMethodName = "/marketing.MarketingService/CreateCampaign"
)

// MarketingServiceClient is the client API for MarketingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 2. Định nghĩa Service (gồm các API)
type MarketingServiceClient interface {
	// API tạo Campaign
	CreateCampaign(ctx context.Context, in *CampaignRequest, opts ...grpc.CallOption) (*CampaignResponse, error)
}

type marketingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketingServiceClient(cc grpc.ClientConnInterface) MarketingServiceClient {
	return &marketingServiceClient{cc}
}

func (c *marketingServiceClient) CreateCampaign(ctx context.Context, in *CampaignRequest, opts ...grpc.CallOption) (*CampaignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CampaignResponse)
	err := c.cc.Invoke(ctx, MarketingService_CreateCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketingServiceServer is the server API for MarketingService service.
// All implementations must embed UnimplementedMarketingServiceServer
// for forward compatibility.
//
// 2. Định nghĩa Service (gồm các API)
type MarketingServiceServer interface {
	// API tạo Campaign
	CreateCampaign(context.Context, *CampaignRequest) (*CampaignResponse, error)
	mustEmbedUnimplementedMarketingServiceServer()
}

// UnimplementedMarketingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarketingServiceServer struct{}

func (UnimplementedMarketingServiceServer) CreateCampaign(context.Context, *CampaignRequest) (*CampaignResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCampaign not implemented")
}
func (UnimplementedMarketingServiceServer) mustEmbedUnimplementedMarketingServiceServer() {}
func (UnimplementedMarketingServiceServer) testEmbeddedByValue()                          {}

// UnsafeMarketingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketingServiceServer will
// result in compilation errors.
type UnsafeMarketingServiceServer interface {
	mustEmbedUnimplementedMarketingServiceServer()
}

func RegisterMarketingServiceServer(s grpc.ServiceRegistrar, srv MarketingServiceServer) {
	// If the following call panics, it indicates UnimplementedMarketingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarketingService_ServiceDesc, srv)
}

func _MarketingService_CreateCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServiceServer).CreateCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketingService_CreateCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServiceServer).CreateCampaign(ctx, req.(*CampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MarketingService_ServiceDesc is the grpc.ServiceDesc for MarketingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "marketing.MarketingService",
	HandlerType: (*MarketingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCampaign",
			Handler:    _MarketingService_CreateCampaign_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
