// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: service.proto

package pb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 1. Định nghĩa Data Structure (giống như struct trong Go hoặc class trong Java)
type CampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                                   // Tên chiến dịch (VD: Khuyến mãi hè)
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                             // Nội dung thông báo
	TargetUsers   int32                  `protobuf:"varint,3,opt,name=target_users,json=targetUsers,proto3" json:"target_users,omitempty"` // Số lượng user muốn gửi thử (giả lập)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CampaignRequest) Reset() {
	*x = CampaignRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignRequest) ProtoMessage() {}

func (x *CampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignRequest.ProtoReflect.Descriptor instead.
func (*CampaignRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *CampaignRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CampaignRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CampaignRequest) GetTargetUsers() int32 {
	if x != nil {
		return x.TargetUsers
	}
	return 0
}

type CampaignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CampaignResponse) Reset() {
	*x = CampaignResponse{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignResponse) ProtoMessage() {}

func (x *CampaignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignResponse.ProtoReflect.Descriptor instead.
func (*CampaignResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *CampaignResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CampaignResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CampaignResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\tmarketing\x1a\x1cgoogle/api/annotations.proto\"b\n" +
	"\x0fCampaignRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12!\n" +
	"\ftarget_users\x18\x03 \x01(\x05R\vtargetUsers\"T\n" +
	"\x10CampaignResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2w\n" +
	"\x10MarketingService\x12c\n" +
	"\x0eCreateCampaign\x12\x1a.marketing.CampaignRequest\x1a\x1b.marketing.CampaignResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/campaignsB\x13Z\x11mini-marketing/pbb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_proto_goTypes = []any{
	(*CampaignRequest)(nil),  // 0: marketing.CampaignRequest
	(*CampaignResponse)(nil), // 1: marketing.CampaignResponse
}
var file_service_proto_depIdxs = []int32{
	0, // 0: marketing.MarketingService.CreateCampaign:input_type -> marketing.CampaignRequest
	1, // 1: marketing.MarketingService.CreateCampaign:output_type -> marketing.CampaignResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
