// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: service.proto

package pb

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CampaignRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CampaignRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CampaignRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CampaignRequestMultiError, or nil if none found.
func (m *CampaignRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CampaignRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetName()); l < 5 || l > 255 {
		err := CampaignRequestValidationError{
			field:  "Name",
			reason: "value length must be between 5 and 255 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetContent()) < 1 {
		err := CampaignRequestValidationError{
			field:  "Content",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetTargetUsers() <= 0 {
		err := CampaignRequestValidationError{
			field:  "TargetUsers",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return CampaignRequestMultiError(errors)
	}

	return nil
}

// CampaignRequestMultiError is an error wrapping multiple validation errors
// returned by CampaignRequest.ValidateAll() if the designated constraints
// aren't met.
type CampaignRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CampaignRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CampaignRequestMultiError) AllErrors() []error { return m }

// CampaignRequestValidationError is the validation error returned by
// CampaignRequest.Validate if the designated constraints aren't met.
type CampaignRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CampaignRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CampaignRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CampaignRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CampaignRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CampaignRequestValidationError) ErrorName() string { return "CampaignRequestValidationError" }

// Error satisfies the builtin error interface
func (e CampaignRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCampaignRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CampaignRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CampaignRequestValidationError{}

// Validate checks the field values on CampaignResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CampaignResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CampaignResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CampaignResponseMultiError, or nil if none found.
func (m *CampaignResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CampaignResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Status

	// no validation rules for Message

	if len(errors) > 0 {
		return CampaignResponseMultiError(errors)
	}

	return nil
}

// CampaignResponseMultiError is an error wrapping multiple validation errors
// returned by CampaignResponse.ValidateAll() if the designated constraints
// aren't met.
type CampaignResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CampaignResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CampaignResponseMultiError) AllErrors() []error { return m }

// CampaignResponseValidationError is the validation error returned by
// CampaignResponse.Validate if the designated constraints aren't met.
type CampaignResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CampaignResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CampaignResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CampaignResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CampaignResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CampaignResponseValidationError) ErrorName() string { return "CampaignResponseValidationError" }

// Error satisfies the builtin error interface
func (e CampaignResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCampaignResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CampaignResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CampaignResponseValidationError{}
